#!/usr/bin/env python3
"""Builds the gzipped web assets embedded in the firmware.

  web/setup.html     -> WEB_SETUP_GZ     (captive portal, hotspot mode)
  web/settings.html  -> WEB_SETTINGS_GZ  (settings page, home network)

Output: src/firmware/web/web_assets.h (committed; regenerated automatically
by PlatformIO as a pre-build step, or run this script by hand).

It also checks that every page's I18N dictionary has exactly the same keys
for "de" and "en" and fails the build otherwise.
"""
import gzip
import io
import os
import re
import sys

try:  # running as a PlatformIO extra_script
    Import("env")  # noqa: F821
    ROOT = env.subst("$PROJECT_DIR")  # noqa: F821
except NameError:
    ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

PAGES = [("setup.html", "WEB_SETUP_GZ"), ("settings.html", "WEB_SETTINGS_GZ")]
OUT = os.path.join(ROOT, "src", "firmware", "web", "web_assets.h")


def check_i18n(name, html):
    m = re.search(r"const I18N=\{\s*de:\{(.*?)\},\s*en:\{(.*?)\}\};", html, re.S)
    if not m:
        raise SystemExit(f"build_web: {name}: I18N dictionary not found")

    def keys(block):
        return set(re.findall(r'(?:^|,)\s*([A-Za-z_][A-Za-z0-9_]*)\s*:', block))

    de, en = keys(m.group(1)), keys(m.group(2))
    if de != en:
        raise SystemExit(f"build_web: {name}: DE/EN key mismatch: only DE {sorted(de - en)}, "
                         f"only EN {sorted(en - de)}")
    used = set(re.findall(r'data-tp?="([A-Za-z_]+)"', html))
    used |= set(re.findall(r'\bt\("([A-Za-z_]+)"[,)]', html))  # literal keys only
    missing = used - de
    if missing:
        raise SystemExit(f"build_web: {name}: keys used but not translated: {sorted(missing)}")
    return len(de)


def minify(html):
    # Conservative: drop indentation and blank lines only (keeps JS intact).
    lines = [ln.strip() for ln in html.splitlines()]
    return "\n".join(ln for ln in lines if ln and not ln.startswith("<!-- "))


def build():
    parts = ["// Generated by tools/build_web.py - do not edit. Sources: web/*.html",
             "#pragma once", "#include <stddef.h>", "#include <stdint.h>", ""]
    summary = []
    for fname, sym in PAGES:
        with open(os.path.join(ROOT, "web", fname), encoding="utf-8") as f:
            html = f.read()
        nkeys = check_i18n(fname, html)
        raw = minify(html).encode("utf-8")
        buf = io.BytesIO()
        with gzip.GzipFile(fileobj=buf, mode="wb", compresslevel=9, mtime=0) as gz:
            gz.write(raw)
        data = buf.getvalue()
        parts.append(f"// {fname}: {len(raw)} bytes -> {len(data)} bytes gzip, {nkeys} i18n keys")
        parts.append(f"static const uint8_t {sym}[] = {{")
        for i in range(0, len(data), 24):
            parts.append("  " + ",".join(f"0x{b:02x}" for b in data[i:i + 24]) + ",")
        parts.append("};")
        parts.append(f"static const size_t {sym}_LEN = {len(data)};")
        parts.append("")
        summary.append(f"{fname} {len(data)}B")
    text = "\n".join(parts)
    old = None
    if os.path.exists(OUT):
        with open(OUT, encoding="utf-8") as f:
            old = f.read()
    if old != text:
        os.makedirs(os.path.dirname(OUT), exist_ok=True)
        with open(OUT, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
        print("build_web: wrote", os.path.relpath(OUT, ROOT), "(" + ", ".join(summary) + ")")


build()
