#!/usr/bin/env python3
"""Generate anti-aliased VLW fonts (Processing / TFT_eSPI / LovyanGFX format) from
the Inter TTFs in tools/fonts and embed them as PROGMEM arrays.

Usage:  pip install freetype-py && python3 tools/gen_fonts.py
Output: lib/ui/src/fonts/*.h  (committed, so a normal build does not need Python deps)

VLW layout (all integers 32-bit big-endian):
  header : glyphCount, version(11), fontSize, 0, ascent, descent
  glyphs : unicode, height, width, xAdvance, dY(top above baseline), dX(left), 0
  bitmaps: width*height bytes of 8-bit alpha per glyph, same order as headers
Glyphs must be sorted by code point (LovyanGFX does a binary search).
"""
import os
import struct
import sys

import freetype

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONT_DIR = os.path.join(ROOT, "tools", "fonts")
OUT_DIR = os.path.join(ROOT, "lib", "ui", "src", "fonts")

ASCII = list(range(0x20, 0x7F))
LATIN1 = list(range(0xA0, 0x100))
# Typographic extras that show up in German stop names / MVG service messages.
EXTRAS = [0x2013, 0x2014, 0x2018, 0x2019, 0x201A, 0x201C, 0x201D, 0x201E,
          0x2022, 0x2026, 0x20AC, 0x2190, 0x2191, 0x2192, 0x2193, 0x2212]
TEXT_SET = ASCII + LATIN1 + EXTRAS
DIGITS_SET = [ord(c) for c in " +-.,:%0123456789°"] + [0x2212, 0x2013]

# name, ttf, pixel size, character set
FONTS = [
    ("font_small", "Inter-Medium.ttf", 13, TEXT_SET),
    ("font_body", "Inter-SemiBold.ttf", 17, TEXT_SET),
    ("font_title", "Inter-SemiBold.ttf", 23, TEXT_SET),
    ("font_badge", "Inter-Bold.ttf", 14, ASCII),
    ("font_big", "Inter-Medium.ttf", 44, DIGITS_SET),
]


def build_vlw(ttf_path, px, charset):
    face = freetype.Face(ttf_path)
    face.set_pixel_sizes(0, px)
    flags = freetype.FT_LOAD_RENDER | freetype.FT_LOAD_TARGET_LIGHT
    headers, bitmaps = [], []
    for cp in sorted(set(charset)):
        if face.get_char_index(cp) == 0:
            print(f"  warning: U+{cp:04X} missing in {os.path.basename(ttf_path)}", file=sys.stderr)
            continue
        face.load_char(chr(cp), flags)
        g = face.glyph
        bm = g.bitmap
        w, h = bm.width, bm.rows
        pitch = bm.pitch
        data = bytearray()
        for row in range(h):
            data += bytes(bm.buffer[row * pitch: row * pitch + w])
        adv = int(round(g.advance.x / 64.0))
        if w > 255 or adv > 255:
            raise SystemExit("glyph too large for VLW uint8 fields")
        headers.append(struct.pack(">7i", cp, h, w, adv, g.bitmap_top, g.bitmap_left, 0))
        bitmaps.append(bytes(data))
    asc = face.size.ascender >> 6
    desc = abs(face.size.descender >> 6)
    out = struct.pack(">6i", len(headers), 11, px, 0, asc, desc)
    out += b"".join(headers) + b"".join(bitmaps)
    return out, len(headers)


def write_header(name, blob, src, px, count):
    path = os.path.join(OUT_DIR, name + ".h")
    lines = [
        "// Generated by tools/gen_fonts.py - do not edit.",
        f"// Source: {src} @ {px}px, {count} glyphs, {len(blob)} bytes. Inter is SIL OFL 1.1.",
        "#pragma once",
        "#include <stdint.h>",
        f"static const uint8_t {name}_vlw[] PROGMEM = {{",
    ]
    for i in range(0, len(blob), 24):
        lines.append("  " + ",".join(f"0x{b:02x}" for b in blob[i:i + 24]) + ",")
    lines.append("};")
    lines.append(f"static const uint32_t {name}_vlw_len = {len(blob)};")
    with open(path, "w", newline="\n") as f:
        f.write("\n".join(lines) + "\n")


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    for name, ttf, px, charset in FONTS:
        blob, count = build_vlw(os.path.join(FONT_DIR, ttf), px, charset)
        write_header(name, blob, ttf, px, count)
        print(f"{name}: {ttf} {px}px -> {count} glyphs, {len(blob)} bytes")


if __name__ == "__main__":
    main()
